[package]
name = "counter_tuto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
crossterm = "0.27.0"
crossbeam = "0.8.2"
ratatui = "0.24.0"
rand = "0.8.5"
